### ISSUE TITLE
Basic Map Generation?

### ISSUE THREAD

**Issue by Kassicus** [Kassicus/project-dawn#3]
Do we want to play around with a noise engine to create random rooms? Or start with a hard coded map for simplicity?

(I have never used a noise engine for room generation, although I have used one for a particle system... They are a pain in the ass)

**Comment by metaphysicalcrab** [comment]
I vote we start with hard coded map for simplicity, but leave room to update it because that sounds cool

**Comment by Kassicus** [comment]
> I vote we start with hard coded map for simplicity, but leave room to update it because that sounds cool

I agree completely, I think thats the best place to start. If we feel good about random generation later, we just make sure we have really good bones and then go from there.

**Comment by Kassicus** [comment]
With that im going to update this to enhancement and we can get rolling with it
